version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "6000:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: main
      POSTGRES_DB: people
